CREATE TABLE  IF NOT EXISTS Account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    address VARCHAR(50) NOT NULL UNIQUE,
    amount VARCHAR (50) NOT NULL
    );

